$specs = @(
    @{ File = "$PSScriptRoot/Appliance.json";    Service = 'Appliance';    },
    @{ File = "$PSScriptRoot/Core.json";         Service = 'Core';         },
    @{ File = "$PSScriptRoot/Notification.json"; Service = 'Notification'; }
)

$entries = [System.Collections.Generic.List[string]]::new()
$segments = @{}

foreach ($spec in $specs) {
    $json = Get-Content $spec.File -Raw | ConvertFrom-Json
    $svc = $spec.Service

    foreach ($pathProp in $json.paths.PSObject.Properties) {
        $apiPath = $pathProp.Name

        if ($apiPath -match '^/v4/([^/{]+)') {
            $seg = $Matches[1]
            if (-not $segments.ContainsKey($svc)) { $segments[$svc] = [System.Collections.Generic.HashSet[string]]::new() }
            [void]$segments[$svc].Add($seg)
        }

        foreach ($methodProp in $pathProp.Value.PSObject.Properties) {
            $httpMethod = $methodProp.Name.ToUpper()
            if ($httpMethod -notin @('GET','POST','PUT','DELETE')) { continue }
            $op = $methodProp.Value

            $isBinaryOnly = $false
            if ($op.responses) {
                $successResp = $null
                foreach ($rp in $op.responses.PSObject.Properties) {
                    if ($rp.Name -match '^2') { $successResp = $rp.Value; break }
                }
                if ($successResp -and $successResp.content) {
                    $contentTypes = $successResp.content.PSObject.Properties.Name
                    if ($contentTypes -contains 'application/octet-stream' -and $contentTypes -notcontains 'application/json') {
                        $isBinaryOnly = $true
                    }
                }
            }
            if ($isBinaryOnly) { continue }

            $summary = ''
            if ($op.summary) { $summary = $op.summary.Trim().TrimEnd('.') }
            $summary = $summary -replace '\\', '\\\\'
            $summary = $summary -replace '"', '\"'
            $summary = $summary -replace "`r`n", ' '
            $summary = $summary -replace "`n", ' '
            $summary = $summary -replace '\s+', ' '

            $paramNames = @()
            if ($op.parameters) {
                foreach ($p in $op.parameters) {
                    $paramNames += $p.name
                }
            }
            $paramsStr = ($paramNames -join ', ')

            $hasBody = if ($null -ne $op.requestBody) { 'true' } else { 'false' }

            $line = '        new("' + $svc + '", "' + $httpMethod + '", "' + $apiPath + '", "' + $summary + '", "' + $paramsStr + '", ' + $hasBody + ')'
            $entries.Add($line)
        }
    }
}

$segmentInfo = @{}
foreach ($svc in $segments.Keys) {
    $sorted = $segments[$svc] | Sort-Object
    $segmentInfo[$svc] = $sorted -join ', '
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Auto-generated by GenerateCatalog.ps1. Do not edit.')
$lines.Add('')
$lines.Add('namespace SafeguardMcp.Tools;')
$lines.Add('')
$lines.Add('public static class SafeguardCatalog')
$lines.Add('{')
$lines.Add('    public readonly record struct ApiEndpoint(string Service, string Method, string Path, string Summary, string Params, bool HasBody);')
$lines.Add('')
$lines.Add('    public static readonly ApiEndpoint[] Endpoints =')
$lines.Add('    [')

for ($i = 0; $i -lt $entries.Count; $i++) {
    $comma = if ($i -lt $entries.Count - 1) { ',' } else { '' }
    $lines.Add($entries[$i] + $comma)
}

$lines.Add('    ];')
$lines.Add('')

foreach ($svc in @('Appliance', 'Core', 'Notification')) {
    if ($segmentInfo.ContainsKey($svc)) {
        $val = $segmentInfo[$svc]
        $lines.Add('    public const string ' + $svc + 'Segments = "' + $val + '";')
    }
}

$lines.Add('}')

$outPath = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\\src\\SafeguardMcp\\Catalog\\StaticCatalog.cs'))
$lines -join "`r`n" | Set-Content -Path $outPath -Encoding UTF8 -NoNewline

Write-Host ('Generated StaticCatalog.cs with ' + $entries.Count + ' endpoints.')
foreach ($svc in @('Appliance', 'Core', 'Notification')) {
    if ($segments.ContainsKey($svc)) {
        Write-Host ('  ' + $svc + ' segments (' + $segments[$svc].Count + '): ' + $segmentInfo[$svc])
    }
}
